# Generated by Django 4.2.16 on 2024-10-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pass_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_salt',
        ),
    ]
