# Generated by Django 4.2.16 on 2025-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemail',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
