# Generated by Django 4.2.16 on 2025-07-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('invoice_name', models.CharField(max_length=150)),
                ('invoice_address', models.CharField(max_length=150)),
                ('contact_telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('postcode_from', models.CharField(max_length=50)),
                ('postcode_to', models.CharField(max_length=50)),
                ('company_from', models.CharField(blank=True, max_length=50, null=True)),
                ('company_to', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_collect_from', models.CharField(max_length=100)),
                ('time_to_collect_to', models.CharField(blank=True, max_length=100, null=True)),
                ('time_to_deliver_from', models.CharField(max_length=100)),
                ('time_to_deliver_to', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
