# Generated by Django 4.2.16 on 2025-07-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='postcode_from',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='postcode_to',
            field=models.CharField(max_length=150),
        ),
    ]
