# Generated by Django 4.2.16 on 2025-07-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.PositiveIntegerField(unique=True)),
                ('invoice_name', models.CharField(max_length=150)),
                ('invoice_address', models.CharField(max_length=150)),
                ('postcode_from', models.CharField(max_length=150)),
                ('postcode_to', models.CharField(max_length=150)),
                ('company_from', models.CharField(blank=True, max_length=50, null=True)),
                ('company_to', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_collect', models.DateTimeField(blank=True, null=True)),
                ('time_to_deliver', models.DateTimeField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
