# Generated by Django 4.2.16 on 2025-07-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0002_alter_quote_postcode_from_alter_quote_postcode_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('invoice_name', models.CharField(max_length=150)),
                ('invoice_address', models.CharField(max_length=150)),
                ('contact_telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('postcode_from', models.CharField(max_length=150)),
                ('postcode_to', models.CharField(max_length=150)),
                ('company_from', models.CharField(blank=True, max_length=50, null=True)),
                ('company_to', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_collect_from', models.CharField(max_length=100)),
                ('time_to_collect_to', models.CharField(blank=True, max_length=100, null=True)),
                ('time_to_deliver_from', models.CharField(max_length=100)),
                ('time_to_deliver_to', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
