# Generated by Django 4.2.16 on 2025-07-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_additional_service_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='additional_info',
            new_name='notes',
        ),
    ]
